recipe: default.v1

assistant_id: RAKUTEN_CALM_TESTING

language: en
pipeline:
  - name: SingleStepLLMCommandGenerator
    flow_retrieval:
      active: false
    # flow_retrieval:
    #   embeddings:
    #     provider: azure
    #     deployment: ai-textembed3small-poc-eus-rasaembedding
    #     api_base: https://ai-openai-poc-eus-rasaembedding.openai.azure.com/
    #     api_type: azure
    #     api_version: "2024-06-01"
    #     timeout: 7
    llm:
      model: gpt-4
      api_type: azure
      api_base: https://ai-openai-poc-eus-llmchatbot.openai.azure.com
      api_version: "2024-06-01"
      deployment: ai-gpt4o-poc-eus-llmchatbot

policies:
  - name: FlowPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy

